version: '2'
services:
  wp:
    depends_on:
     - base
    image:  wordpress:latest
    volumes:
     - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
     - ./data:/var/www/html
    ports:
     - 84:84
    restart: always
    environment:
     WORDPRESS_DB_HOST: base
     WORDPRESS_DB_USER: root
     WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
     WORDPRESS_DB_NAME: "${DB_NAME}"
  base:
    image: mysql
    ports:
     - 3306:3306
    volumes:
     - ./db-dump:/docker-entrypointinitdb.d
     - db_data:/var/lib/mysql/
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
     MYSQL_DATABASE: "${DB_NAME}"
volumes:
  db_data:
